let character_walk=[
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_0.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_1.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_2.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_3.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_4.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_5.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_6.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_7.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_8.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_9.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_10.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_11.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_12.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_13.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_14.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_15.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_16.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Walk/Wukong-Walk_17.png",
  ];

  let character_jump=[
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Jump/Wukong-Jump_0.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Jump/Wukong-Jump_1.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Jump/Wukong-Jump_2.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Jump/Wukong-Jump_3.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Jump/Wukong-Jump_4.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Jump/Wukong-Jump_5.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Jump/Wukong-Jump_6.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Jump/Wukong-Jump_7.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Jump/Wukong-Jump_8.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Jump/Wukong-Jump_9.png",
  ];


  let character_throw=[
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_0.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_1.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_2.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_3.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_4.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_5.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_6.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_7.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_8.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_9.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_10.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_11.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_12.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_13.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_14.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_15.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_16.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_17.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_18.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_19.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Throw/Wukong-Throw_20.png",
  ];


  let character_hit= [
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_0.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_1.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_2.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_3.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_4.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_5.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_6.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_7.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_8.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_9.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_10.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_11.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_12.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_13.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_14.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_15.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_16.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_17.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_18.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_19.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_20.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Hit/Wukong-Hit_21.png",
  ];

  let character_gethit = [
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_0.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_1.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_2.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_3.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_4.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_5.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_6.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_7.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_8.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_9.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_10.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_11.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_12.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/GetHit/Wukong-GetHit_13.png",
  ];

  let character_die = [
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_0.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_1.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_2.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_3.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_4.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_5.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_6.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_7.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_8.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_9.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_10.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_11.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_12.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_13.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_14.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_15.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_16.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_17.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_18.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_19.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_20.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_21.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_22.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_23.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_24.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Die/Wukong-Death_25.png",
  ];

  

   let character_celabrates= [
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_0.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_1.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_2.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_3.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_4.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_5.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_6.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_7.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_8.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_9.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_10.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_11.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_12.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Celebrates/Wukong-Celebrates_13.png",
  ];

  let character_glide=[
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Glide/Wukong-Glide_0.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Glide/Wukong-Glide_1.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Glide/Wukong-Glide_2.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Glide/Wukong-Glide_3.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Glide/Wukong-Glide_4.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Glide/Wukong-Glide_5.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Glide/Wukong-Glide_6.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Glide/Wukong-Glide_7.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Glide/Wukong-Glide_8.png",
    "img/craftpix-net-546825-monkey-game-character-sprite/PNG/Glide/Wukong-Glide_9.png",
  ];

  let endboss_walk=[
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_00.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_01.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_02.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_03.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_04.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_05.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_06.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_07.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_08.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_09.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_10.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_11.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_12.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_13.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_14.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_15.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_16.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_17.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_18.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Walk/Walk_19.png",
  ];

  let endboss_dead=[
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_00.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_01.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_02.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_03.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_04.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_00.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_05.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_06.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_07.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_08.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_09.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_10.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_11.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_12.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_13.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_14.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_15.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_16.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_17.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_18.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_19.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_20.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_21.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_22.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_23.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_24.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_25.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_26.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_27.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_28.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_29.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_30.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_31.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_32.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_33.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Death/Death_34.png",
  ];

  let endboss_attack=[
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_00.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_01.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_02.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_03.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_04.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_05.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_06.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_07.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_08.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_09.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_10.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_11.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_12.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_13.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_14.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_15.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_16.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_17.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_18.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_19.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_20.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_21.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_22.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_23.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_24.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_25.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_26.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_27.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_28.png",
    "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 02/Attack/Attack_29.png",
  ];

  let enemy_walk=["img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_00.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_01.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_02.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_03.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_04.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_05.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_06.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_07.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_08.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_09.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_10.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_11.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_12.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_13.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_14.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_15.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_16.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_17.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_18.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Walk/Walk_19.png"]


  let enemy_dead=["img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_00.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_01.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_02.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_03.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_04.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_05.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_06.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_07.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_08.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_09.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_10.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_11.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_12.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_13.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_14.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_15.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_16.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_17.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_18.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_19.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_20.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_21.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_22.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_23.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_24.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_25.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_26.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_27.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_28.png",
  "img/craftpix-891176-battle-of-heroes-2d-game-kit/Png/Characters/Characters 04/Death/Death_29.png"
  ]
  
